### ISSUE TITLE
Riot League

### ISSUE THREAD

**Issue by ekhoury2000** [zeropingheroes/lancache-sniproxy#1]
Hi @ilumos 
i am having issues with my lancache server for https related games.

I have tried so many docker images and you lancache, but same for all.
League beta client gets stuck and keeps restarting and old league client says(unspecified error occurred)

i have read that you mentioned that https traffic cannot be cached, and sniproxy should pass https trafic, but if true, why bother create a cache server for riot and blizzard while the both use https??

thanks in advance

**Comment by ilumos** [comment]
Hi there,

The Riot downloader will download the game content over HTTP if the DNS
response for its CDN gives a RFC1918 address (10.0.0.0/8 or 172.16.0.0/12
or 192.168.0.0/16). We need sniproxy to allow people who haven't got the
Riot downloader installed to be able to visit
https://signup.na.leagueoflegends.com/en/signup/redownload in their web
browsers, which will default to HTTPS.

As for Blizzard, last time I checked, all game content is served over HTTP
for them.

I hope this answers the question!

As for your unspecified error, I don't know what the solution for that is,
sorry.

Many thanks

**Comment by ekhoury2000** [comment]
Thanks @ilumos But i did not quite get the riot sniproxy part.
i have an sniproxy installed on the server, should it suffice?

**Comment by ilumos** [comment]
Hi there,

Yep, sniproxy will accept any HTTPS connections from computers on your LAN and pass them through to the real Riot servers, allowing them to visit the download webpage and download the launcher. 

Check sniproxy is running OK:
```systemctl status sniproxy```

Hope this helps
