### ISSUE TITLE
Issues with sniproxy and nginx

### ISSUE THREAD

**Issue by marcusboon** [zeropingheroes/lancache-sniproxy#2]
Hi,

I installed this along with lancache and am having issues with https especially with the Blizzard links. Looking at the syslogs and `systemctl status sniproxy` gives me:

>● sniproxy.service - LSB: HTTPS SNI Proxy
   Loaded: loaded (/etc/init.d/sniproxy; generated)
   Active: active (exited) since Fri 2018-09-14 09:28:12 AEST; 6min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 17949 ExecStop=/etc/init.d/sniproxy stop (code=exited, status=0/SUCCESS)
  Process: 17970 ExecStart=/etc/init.d/sniproxy start (code=exited, status=0/SUCCESS)
>
>Sep 14 09:28:12 malachor.home systemd[1]: Starting LSB: HTTPS SNI Proxy...
Sep 14 09:28:12 malachor.home systemd[1]: Started LSB: HTTPS SNI Proxy.
Sep 14 09:28:12 malachor.home sniproxy[17990]: bind 0.0.0.0:443 failed: Address already in use
Sep 14 09:28:12 malachor.home sniproxy[17990]: Failed to initialize listener 0.0.0.0:443

It seems like nginx is already listening on port 443 for all connections
>marcus@malachor:/etc/nginx$ sudo netstat -tulpn | grep :443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      18568/nginx: master

How can I resolve this?

**Comment by marcusboon** [comment]
Ok it looks like because I had another virtualhost listening on port 443 that is what was causing the issue. Removing that virtualhost from my nginx config solved it. But then I wonder how I can have both.

**Comment by ilumos** [comment]
Thanks for this heads up @marcusboon - I've updated the readme for other people

**Comment by marcusboon** [comment]
Hi @ilumos so I managed to resolve it by using sniproxy itself to redirect the https so for instance my /etc/sniproxy.conf now has:

>table allhosts {
    unms.malachor.home 10.0.1.107:8443
    .* *:443
}

**Comment by ilumos** [comment]
Thanks for sharing - someone else may find that useful!
